In [1]:
! pip install finance-datareader

In [2]:
import FinanceDataReader as fdr
from tqdm import tqdm

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 
import os
import itertools
import random

from sklearn.preprocessing import MinMaxScaler, StandardScaler

import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.layers import Dense,  GRU, Concatenate, Dropout, LSTM, SimpleRNN, TimeDistributed, Bidirectional
from tensorflow.keras import Sequential, Input, Model, layers, optimizers
from tensorflow.keras.optimizers import SGD, Adam

In [3]:
random.seed(1234)
np.random.seed(1234)
os.environ["PYTHONHASHSEED"] = str(1234)
tf.random.set_seed(1234)

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
path = '/content/drive/MyDrive/stock_2/'
list_name = 'stock_list.csv'
stock_list = pd.read_csv(os.path.join(path,list_name))
stock_list['종목코드'] = stock_list['종목코드'].apply(lambda x : str(x).zfill(6))
stock_list

종목명    종목코드    상장시장
0        삼성전자  005930   KOSPI
1      SK하이닉스  000660   KOSPI
2       NAVER  035420   KOSPI
3         카카오  035720   KOSPI
4    삼성바이오로직스  207940   KOSPI
..        ...     ...     ...
365      맘스터치  220630  KOSDAQ
366        다날  064260  KOSDAQ
367   제이시스메디칼  287410  KOSDAQ
368   크리스에프앤씨  110790  KOSDAQ
369     쎄트렉아이  099320  KOSDAQ

[370 rows x 3 columns]

# Public

In [6]:
start_date = '20210104'
end_date = '20211105'

start_weekday = pd.to_datetime(start_date).weekday()
max_weeknum = pd.to_datetime(end_date).strftime('%V')
business_days = pd.DataFrame(pd.date_range(start_date,end_date,freq='B'), columns = ['Date'])

In [7]:
def RNN_model(X_train, y_train, X_val, y_val):

  model = Sequential()
  model.add(SimpleRNN(units = 1, input_shape = (X_train.shape[1], 1), activation = 'tanh', return_sequences = True))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))

  model.add(TimeDistributed(Dense(units = 1)))

  model.compile(optimizer = Adam(learning_rate = 0.01), loss = 'mean_absolute_error', metrics=['mae']) 

  es = EarlyStopping(monitor ='val_loss', mode ='min', verbose = 1, patience = 10)
  model_save_folder_path = '/content/drive/MyDrive/stock_2/rnn_public/rnn'
  model_path = model_save_folder_path + f'{code}.h5'
  mc = ModelCheckpoint(model_path, monitor ='val_loss', mode ='min', verbose = 1, save_best_only = True)

  model.fit(X_train, y_train, epochs = 100, batch_size = 2, verbose = 1, shuffle = False, callbacks = [es, mc],
                      validation_data=(X_val, y_val))

  return model

In [8]:
submission_name = 'sample_submission.csv'
submission = pd.read_csv(os.path.join(path,submission_name))

In [9]:
nmae_df = pd.DataFrame(columns = ['code', 'nmae'])

In [10]:
stock_price = fdr.DataReader('000060', start = start_date, end = end_date)[['Close']].reset_index()
stock_price = pd.merge(business_days, stock_price, how = 'outer')
stock_price['weekday'] = stock_price.Date.apply(lambda x : x.weekday())
stock_price['weeknum'] = stock_price.Date.apply(lambda x : x.strftime('%V'))
stock_price.Close = stock_price.Close.ffill()
stock_price = pd.pivot_table(data = stock_price, values = 'Close', columns = 'weekday', index = 'weeknum')

In [11]:
import warnings
warnings.filterwarnings("ignore")

for code in tqdm(stock_list['종목코드'].values):
  tf.random.set_seed(1234)
  
  # 해당 종목의 데이터 가져온 후 주 단위 데이터로 나타내기
  stock_price = fdr.DataReader(code, start = start_date, end = end_date)[['Close']].reset_index()
  stock_price = pd.merge(business_days, stock_price, how = 'outer')
  stock_price['weekday'] = stock_price.Date.apply(lambda x : x.weekday())
  stock_price['weeknum'] = stock_price.Date.apply(lambda x : x.strftime('%V'))
  stock_price.Close = stock_price.Close.ffill()
  stock_price = pd.pivot_table(data = stock_price, values = 'Close', columns = 'weekday', index = 'weeknum')

  X_train = stock_price.iloc[0:-12].to_numpy()
  X_val = stock_price.iloc[-12:-2].to_numpy()
  X_test = stock_price.iloc[-2].to_numpy()

  y_train = stock_price.iloc[1:-11].to_numpy()
  y_val = stock_price.iloc[-11:-1].to_numpy()
  y_test = stock_price.iloc[-1].to_numpy()

  # 스케일링 시행
  scaler = MinMaxScaler()

  X_train_scaled = scaler.fit_transform(X_train.reshape(-1, 1)).reshape(32, 5)
  X_val_scaled = scaler.fit_transform(X_val.reshape(-1, 1)).reshape(10, 5)
  X_test_scaled = scaler.fit_transform(X_test.reshape(-1, 1)).reshape(1, 5)

  y_train_scaled = scaler.fit_transform(y_train.reshape(-1, 1)).reshape(32, 5)
  y_val_scaled = scaler.fit_transform(y_val.reshape(-1, 1)).reshape(10, 5)
  y_test_scaled = scaler.fit_transform(y_test.reshape(-1, 1)).reshape(1, 5)

  X_train_scaled = np.reshape(X_train_scaled, (X_train_scaled.shape[0], X_train_scaled.shape[1]))
  X_val_scaled = np.reshape(X_val_scaled, (X_val_scaled.shape[0], X_val_scaled.shape[1]))
  X_test_scaled = np.reshape(X_test_scaled, (X_test_scaled.shape[0], X_test_scaled.shape[1]))
  
  # 모델 학습
  model = RNN_model(X_train_scaled, y_train_scaled, X_val_scaled, y_val_scaled)
  model = keras.models.load_model(f"/content/drive/MyDrive/stock_2/rnn_public/rnn{code}.h5")

  # 예측
  y_pred = model.predict(X_test_scaled)
  y_pred = y_pred.reshape(1,5)
  y_pred = scaler.inverse_transform(y_pred)

  nmae = np.mean(np.abs(y_test - y_pred) / y_test)

  nmae_df = nmae_df.append({'code' : code, 'nmae' : nmae}, ignore_index = True)
  
  print(y_pred)
  print(nmae)
    
  for i in range (0, 5):
    submission.loc[i, code] = y_pred[0][i]


Epoch 00022: val_loss did not improve from 0.16172
16/16 [==============================] - 0s 11ms/step - loss: 0.1349 - mae: 0.1349 - val_loss: 0.2011 - val_mae: 0.2011
Epoch 23/100
13/16 [=======================>......] - ETA: 0s - loss: 0.1552 - mae: 0.1552
Epoch 00023: val_loss did not improve from 0.16172
16/16 [==============================] - 0s 11ms/step - loss: 0.1552 - mae: 0.1552 - val_loss: 0.1681 - val_mae: 0.1681
Epoch 24/100
13/16 [=======================>......] - ETA: 0s - loss: 0.1165 - mae: 0.1165
Epoch 00024: val_loss did not improve from 0.16172
16/16 [==============================] - 0s 11ms/step - loss: 0.1144 - mae: 0.1144 - val_loss: 0.1812 - val_mae: 0.1812
Epoch 25/100
13/16 [=======================>......] - ETA: 0s - loss: 0.1132 - mae: 0.1132
Epoch 00025: val_loss did not improve from 0.16172
16/16 [==============================] - 0s 12ms/step - loss: 0.1162 - mae: 0.1162 - val_loss: 0.2065 - val_mae: 0.2065
Epoch 26/100
13/16 [======================

 87%|████████▋ | 321/370 [1:15:17<11:57, 14.65s/it]

[[27308.602 27306.049 27281.785 27268.25  27275.225]]
0.021443712245591884
Epoch 1/100
16/16 [==============================] - ETA: 0s - loss: 0.3205 - mae: 0.3205
Epoch 00001: val_loss improved from inf to 0.33653, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn013120.h5
16/16 [==============================] - 5s 67ms/step - loss: 0.3205 - mae: 0.3205 - val_loss: 0.3365 - val_mae: 0.3365
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.4713 - mae: 0.4713
Epoch 00002: val_loss improved from 0.33653 to 0.31383, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn013120.h5
16/16 [==============================] - 0s 18ms/step - loss: 0.4588 - mae: 0.4588 - val_loss: 0.3138 - val_mae: 0.3138
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3658 - mae: 0.3658
Epoch 00003: val_loss improved from 0.31383 to 0.28484, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn013120.h5
16/16 [==============================]

 87%|████████▋ | 322/370 [1:15:34<12:16, 15.34s/it]

[[5217.803 5308.924 5295.357 5194.788 5170.475]]
0.007958844356750299
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2421 - mae: 0.2421
Epoch 00001: val_loss improved from inf to 0.45111, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn095660.h5
16/16 [==============================] - 5s 91ms/step - loss: 0.2842 - mae: 0.2842 - val_loss: 0.4511 - val_mae: 0.4511
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.0757 - mae: 0.0757
Epoch 00002: val_loss improved from 0.45111 to 0.33467, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn095660.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.1182 - mae: 0.1182 - val_loss: 0.3347 - val_mae: 0.3347
Epoch 3/100
12/16 [=====================>........] - ETA: 0s - loss: 0.0969 - mae: 0.0969
Epoch 00003: val_loss did not improve from 0.33467
16/16 [==============================] - 0s 12ms/step - loss: 0.1566 - mae: 0.1566 - val_loss: 0.3945 - val_mae: 0.3945

 87%|████████▋ | 323/370 [1:15:51<12:23, 15.82s/it]

[[26467.117 27182.07  27431.21  27140.297 27169.176]]
0.03692632743101015
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2876 - mae: 0.2876
Epoch 00001: val_loss improved from inf to 0.25551, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn060150.h5
16/16 [==============================] - 5s 66ms/step - loss: 0.2934 - mae: 0.2934 - val_loss: 0.2555 - val_mae: 0.2555
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2709 - mae: 0.2709
Epoch 00002: val_loss improved from 0.25551 to 0.22768, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn060150.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.2601 - mae: 0.2601 - val_loss: 0.2277 - val_mae: 0.2277
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2435 - mae: 0.2435
Epoch 00003: val_loss improved from 0.22768 to 0.22728, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn060150.h5
16/16 [==============================] 

 88%|████████▊ | 324/370 [1:16:05<11:46, 15.35s/it]

[[12061.573 12098.451 12077.954 12041.141 11896.517]]
0.009164431960072923
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3792 - mae: 0.3792
Epoch 00001: val_loss improved from inf to 0.24255, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn061970.h5
16/16 [==============================] - 6s 66ms/step - loss: 0.3776 - mae: 0.3776 - val_loss: 0.2425 - val_mae: 0.2425
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3011 - mae: 0.3011
Epoch 00002: val_loss did not improve from 0.24255
16/16 [==============================] - 0s 11ms/step - loss: 0.2888 - mae: 0.2888 - val_loss: 0.3244 - val_mae: 0.3244
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2632 - mae: 0.2632
Epoch 00003: val_loss did not improve from 0.24255
16/16 [==============================] - 0s 10ms/step - loss: 0.2567 - mae: 0.2567 - val_loss: 0.2742 - val_mae: 0.2742
Epoch 4/100
13/16 [=======================>......] - ETA: 0s - loss: 0

 88%|████████▊ | 325/370 [1:16:22<11:51, 15.82s/it]

[[12598.116 12592.761 12616.772 12654.97  12678.249]]
0.01038034076218378
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2917 - mae: 0.2917
Epoch 00001: val_loss improved from inf to 0.20890, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn095610.h5
16/16 [==============================] - 5s 66ms/step - loss: 0.2933 - mae: 0.2933 - val_loss: 0.2089 - val_mae: 0.2089
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2916 - mae: 0.2916
Epoch 00002: val_loss did not improve from 0.20890
16/16 [==============================] - 0s 11ms/step - loss: 0.2704 - mae: 0.2704 - val_loss: 0.2120 - val_mae: 0.2120
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2091 - mae: 0.2091
Epoch 00003: val_loss did not improve from 0.20890
16/16 [==============================] - 0s 10ms/step - loss: 0.2084 - mae: 0.2084 - val_loss: 0.2182 - val_mae: 0.2182
Epoch 4/100
14/16 [=========================>....] - ETA: 0s - loss: 0.

 88%|████████▊ | 326/370 [1:16:35<11:01, 15.04s/it]

[[26596.414 26573.281 26565.303 26603.63  26641.91 ]]
0.0037561493098937234
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3632 - mae: 0.3632
Epoch 00001: val_loss improved from inf to 0.27407, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn089970.h5
16/16 [==============================] - 5s 91ms/step - loss: 0.3615 - mae: 0.3615 - val_loss: 0.2741 - val_mae: 0.2741
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3576 - mae: 0.3576
Epoch 00002: val_loss improved from 0.27407 to 0.26170, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn089970.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.3485 - mae: 0.3485 - val_loss: 0.2617 - val_mae: 0.2617
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.4079 - mae: 0.4079
Epoch 00003: val_loss improved from 0.26170 to 0.24882, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn089970.h5
16/16 [==============================

 88%|████████▊ | 327/370 [1:16:52<11:08, 15.54s/it]

[[15686.244  16308.925  15796.089  16302.419  15749.1045]]
0.02912315040823532
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.4094 - mae: 0.4094
Epoch 00001: val_loss improved from inf to 0.58706, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn036810.h5
16/16 [==============================] - 5s 66ms/step - loss: 0.4020 - mae: 0.4020 - val_loss: 0.5871 - val_mae: 0.5871
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.4697 - mae: 0.4697
Epoch 00002: val_loss improved from 0.58706 to 0.27937, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn036810.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.4372 - mae: 0.4372 - val_loss: 0.2794 - val_mae: 0.2794
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2825 - mae: 0.2825
Epoch 00003: val_loss did not improve from 0.27937
16/16 [==============================] - 0s 11ms/step - loss: 0.2574 - mae: 0.2574 - val_loss: 0.5116 - val_ma

 89%|████████▊ | 328/370 [1:17:05<10:14, 14.64s/it]

[[25093.012 25133.203 25194.918 25213.205 25270.46 ]]
0.006845464466791386
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3257 - mae: 0.3257
Epoch 00001: val_loss improved from inf to 0.27123, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn348210.h5
16/16 [==============================] - 6s 66ms/step - loss: 0.3255 - mae: 0.3255 - val_loss: 0.2712 - val_mae: 0.2712
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3026 - mae: 0.3026
Epoch 00002: val_loss improved from 0.27123 to 0.25843, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn348210.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.2889 - mae: 0.2889 - val_loss: 0.2584 - val_mae: 0.2584
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3038 - mae: 0.3038
Epoch 00003: val_loss improved from 0.25843 to 0.24544, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn348210.h5
16/16 [==============================]

 89%|████████▉ | 329/370 [1:17:22<10:27, 15.31s/it]

[[51051.367 51024.406 51674.496 52026.426 51852.527]]
0.024815000633109194
Epoch 1/100
16/16 [==============================] - ETA: 0s - loss: 0.3642 - mae: 0.3642
Epoch 00001: val_loss improved from inf to 0.24497, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn330860.h5
16/16 [==============================] - 6s 67ms/step - loss: 0.3642 - mae: 0.3642 - val_loss: 0.2450 - val_mae: 0.2450
Epoch 2/100
12/16 [=====================>........] - ETA: 0s - loss: 0.3517 - mae: 0.3517
Epoch 00002: val_loss did not improve from 0.24497
16/16 [==============================] - 0s 12ms/step - loss: 0.3109 - mae: 0.3109 - val_loss: 0.2474 - val_mae: 0.2474
Epoch 3/100
12/16 [=====================>........] - ETA: 0s - loss: 0.2252 - mae: 0.2252
Epoch 00003: val_loss did not improve from 0.24497
16/16 [==============================] - 0s 12ms/step - loss: 0.2469 - mae: 0.2469 - val_loss: 0.2520 - val_mae: 0.2520
Epoch 4/100
13/16 [=======================>......] - ETA: 0s - loss: 0

 89%|████████▉ | 330/370 [1:17:38<10:31, 15.78s/it]

[[49107.727 48866.793 48885.945 48778.36  48879.195]]
0.017256803154442522
Epoch 1/100
 9/16 [===============>..............] - ETA: 0s - loss: 0.2923 - mae: 0.2923 
Epoch 00001: val_loss improved from inf to 0.27972, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn263720.h5
16/16 [==============================] - 5s 90ms/step - loss: 0.2767 - mae: 0.2767 - val_loss: 0.2797 - val_mae: 0.2797
Epoch 2/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3452 - mae: 0.3452
Epoch 00002: val_loss improved from 0.27972 to 0.17479, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn263720.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.3319 - mae: 0.3319 - val_loss: 0.1748 - val_mae: 0.1748
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2707 - mae: 0.2707
Epoch 00003: val_loss did not improve from 0.17479
16/16 [==============================] - 0s 11ms/step - loss: 0.2502 - mae: 0.2502 - val_loss: 0.2469 - val_mae: 

 89%|████████▉ | 331/370 [1:17:50<09:20, 14.37s/it]

[[40691.887 40525.152 40645.465 40585.58  40621.637]]
0.026599733336816755
Epoch 1/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2961 - mae: 0.2961
Epoch 00001: val_loss improved from inf to 0.23087, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn143240.h5
16/16 [==============================] - 5s 66ms/step - loss: 0.3208 - mae: 0.3208 - val_loss: 0.2309 - val_mae: 0.2309
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2574 - mae: 0.2574
Epoch 00002: val_loss did not improve from 0.23087
16/16 [==============================] - 0s 11ms/step - loss: 0.2655 - mae: 0.2655 - val_loss: 0.2926 - val_mae: 0.2926
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.4205 - mae: 0.4205
Epoch 00003: val_loss did not improve from 0.23087
16/16 [==============================] - 0s 11ms/step - loss: 0.4419 - mae: 0.4419 - val_loss: 0.3539 - val_mae: 0.3539
Epoch 4/100
14/16 [=========================>....] - ETA: 0s - loss: 0

 90%|████████▉ | 332/370 [1:18:00<08:25, 13.29s/it]

[[46262.562 46531.41  46586.305 46187.04  45841.254]]
0.021223858231734654
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3320 - mae: 0.3320
Epoch 00001: val_loss improved from inf to 0.25806, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn091700.h5
16/16 [==============================] - 6s 66ms/step - loss: 0.3303 - mae: 0.3303 - val_loss: 0.2581 - val_mae: 0.2581
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2642 - mae: 0.2642
Epoch 00002: val_loss improved from 0.25806 to 0.25777, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn091700.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.2479 - mae: 0.2479 - val_loss: 0.2578 - val_mae: 0.2578
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2391 - mae: 0.2391
Epoch 00003: val_loss did not improve from 0.25777
16/16 [==============================] - 0s 11ms/step - loss: 0.2307 - mae: 0.2307 - val_loss: 0.3476 - val_mae: 0

 90%|█████████ | 333/370 [1:18:11<07:38, 12.39s/it]

[[9776.907  9679.9375 9761.697  9821.238  9825.741 ]]
0.0410170510752418
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2477 - mae: 0.2477
Epoch 00001: val_loss improved from inf to 0.32327, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn067000.h5
16/16 [==============================] - 5s 67ms/step - loss: 0.2452 - mae: 0.2452 - val_loss: 0.3233 - val_mae: 0.3233
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.3340 - mae: 0.3340
Epoch 00002: val_loss improved from 0.32327 to 0.20086, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn067000.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.3476 - mae: 0.3476 - val_loss: 0.2009 - val_mae: 0.2009
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2392 - mae: 0.2392
Epoch 00003: val_loss did not improve from 0.20086
16/16 [==============================] - 0s 11ms/step - loss: 0.2611 - mae: 0.2611 - val_loss: 0.2054 - val_mae: 0.2

 90%|█████████ | 334/370 [1:18:20<06:56, 11.57s/it]

[[11480.876 11528.285 11608.78  11614.47  11610.368]]
0.03445701923595791
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3549 - mae: 0.3549
Epoch 00001: val_loss improved from inf to 0.22904, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn204270.h5
16/16 [==============================] - 5s 94ms/step - loss: 0.3531 - mae: 0.3531 - val_loss: 0.2290 - val_mae: 0.2290
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2840 - mae: 0.2840
Epoch 00002: val_loss improved from 0.22904 to 0.22329, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn204270.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.2758 - mae: 0.2758 - val_loss: 0.2233 - val_mae: 0.2233
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2549 - mae: 0.2549
Epoch 00003: val_loss improved from 0.22329 to 0.21064, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn204270.h5
16/16 [==============================] 

 91%|█████████ | 335/370 [1:18:30<06:26, 11.04s/it]

[[8344.43  8304.544 8266.5   8314.712 8274.751]]
0.00771360584619739
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2601 - mae: 0.2601
Epoch 00001: val_loss improved from inf to 0.25431, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn032190.h5
16/16 [==============================] - 5s 67ms/step - loss: 0.2671 - mae: 0.2671 - val_loss: 0.2543 - val_mae: 0.2543
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.3276 - mae: 0.3276
Epoch 00002: val_loss improved from 0.25431 to 0.21438, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn032190.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.3124 - mae: 0.3124 - val_loss: 0.2144 - val_mae: 0.2144
Epoch 3/100
12/16 [=====================>........] - ETA: 0s - loss: 0.3220 - mae: 0.3220
Epoch 00003: val_loss did not improve from 0.21438
16/16 [==============================] - 0s 12ms/step - loss: 0.3221 - mae: 0.3221 - val_loss: 0.2797 - val_mae: 0.2797


 91%|█████████ | 336/370 [1:18:40<05:59, 10.56s/it]

[[13783.331 13780.069 13831.571 13777.345 13841.535]]
0.0065168135196481194
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3560 - mae: 0.3560
Epoch 00001: val_loss improved from inf to 0.28315, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn131370.h5
16/16 [==============================] - 6s 65ms/step - loss: 0.3539 - mae: 0.3539 - val_loss: 0.2832 - val_mae: 0.2832
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.3342 - mae: 0.3342
Epoch 00002: val_loss improved from 0.28315 to 0.26988, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn131370.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.3391 - mae: 0.3391 - val_loss: 0.2699 - val_mae: 0.2699
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2577 - mae: 0.2577
Epoch 00003: val_loss did not improve from 0.26988
16/16 [==============================] - 0s 11ms/step - loss: 0.2682 - mae: 0.2682 - val_loss: 0.2943 - val_mae: 

 91%|█████████ | 337/370 [1:18:55<06:40, 12.13s/it]

[[7505.8735 7651.1865 7687.2144 7579.1416 7537.834 ]]
0.0179064105761739
Epoch 1/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2892 - mae: 0.2892
Epoch 00001: val_loss improved from inf to 0.27553, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn321550.h5
16/16 [==============================] - 5s 67ms/step - loss: 0.2813 - mae: 0.2813 - val_loss: 0.2755 - val_mae: 0.2755
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.3230 - mae: 0.3230
Epoch 00002: val_loss improved from 0.27553 to 0.24572, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn321550.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.3342 - mae: 0.3342 - val_loss: 0.2457 - val_mae: 0.2457
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2754 - mae: 0.2754
Epoch 00003: val_loss did not improve from 0.24572
16/16 [==============================] - 0s 11ms/step - loss: 0.3077 - mae: 0.3077 - val_loss: 0.3253 - val_mae: 0.3

 91%|█████████▏| 338/370 [1:19:09<06:46, 12.71s/it]

[[18855.68  18874.229 18844.38  18835.775 18775.334]]
0.008960294344725665
Epoch 1/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2757 - mae: 0.2757
Epoch 00001: val_loss improved from inf to 0.21937, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn347860.h5
16/16 [==============================] - 5s 66ms/step - loss: 0.2710 - mae: 0.2710 - val_loss: 0.2194 - val_mae: 0.2194
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2556 - mae: 0.2556
Epoch 00002: val_loss did not improve from 0.21937
16/16 [==============================] - 0s 11ms/step - loss: 0.2656 - mae: 0.2656 - val_loss: 0.3220 - val_mae: 0.3220
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.1468 - mae: 0.1468
Epoch 00003: val_loss did not improve from 0.21937
16/16 [==============================] - 0s 11ms/step - loss: 0.1582 - mae: 0.1582 - val_loss: 0.2856 - val_mae: 0.2856
Epoch 4/100
14/16 [=========================>....] - ETA: 0s - loss: 0

 92%|█████████▏| 339/370 [1:19:19<06:01, 11.67s/it]

[[35307.168 35285.332 35617.246 35896.402 35990.293]]
0.021284504638659732
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.1509 - mae: 0.1509
Epoch 00001: val_loss improved from inf to 0.25085, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn003800.h5
16/16 [==============================] - 5s 69ms/step - loss: 0.1559 - mae: 0.1559 - val_loss: 0.2509 - val_mae: 0.2509
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2207 - mae: 0.2207
Epoch 00002: val_loss improved from 0.25085 to 0.22902, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn003800.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.2121 - mae: 0.2121 - val_loss: 0.2290 - val_mae: 0.2290
Epoch 3/100
12/16 [=====================>........] - ETA: 0s - loss: 0.1816 - mae: 0.1816
Epoch 00003: val_loss did not improve from 0.22902
16/16 [==============================] - 0s 11ms/step - loss: 0.1877 - mae: 0.1877 - val_loss: 0.2480 - val_mae: 0

 92%|█████████▏| 340/370 [1:19:28<05:30, 11.01s/it]

[[47523.918 47505.273 47516.895 47573.492 47530.137]]
0.00395669662974514
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2972 - mae: 0.2972
Epoch 00001: val_loss improved from inf to 0.26832, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn032300.h5
16/16 [==============================] - 6s 66ms/step - loss: 0.2920 - mae: 0.2920 - val_loss: 0.2683 - val_mae: 0.2683
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2428 - mae: 0.2428
Epoch 00002: val_loss improved from 0.26832 to 0.25495, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn032300.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.2416 - mae: 0.2416 - val_loss: 0.2550 - val_mae: 0.2550
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.1993 - mae: 0.1993
Epoch 00003: val_loss improved from 0.25495 to 0.25387, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn032300.h5
16/16 [==============================] 

 92%|█████████▏| 341/370 [1:19:38<05:11, 10.75s/it]

[[56846.637 56523.555 56543.832 56431.945 57290.77 ]]
0.04251934102757056
Epoch 1/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3108 - mae: 0.3108
Epoch 00001: val_loss improved from inf to 0.30047, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn122450.h5
16/16 [==============================] - 5s 68ms/step - loss: 0.3013 - mae: 0.3013 - val_loss: 0.3005 - val_mae: 0.3005
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2617 - mae: 0.2617
Epoch 00002: val_loss improved from 0.30047 to 0.19542, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn122450.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.2574 - mae: 0.2574 - val_loss: 0.1954 - val_mae: 0.1954
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2193 - mae: 0.2193
Epoch 00003: val_loss did not improve from 0.19542
16/16 [==============================] - 0s 11ms/step - loss: 0.2120 - mae: 0.2120 - val_loss: 0.2282 - val_mae: 0.

 92%|█████████▏| 342/370 [1:19:51<05:21, 11.49s/it]

[[8690.515 8760.26  8697.64  8644.396 8590.856]]
0.013057705557127815
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2959 - mae: 0.2959
Epoch 00001: val_loss improved from inf to 0.32008, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn206640.h5
16/16 [==============================] - 5s 65ms/step - loss: 0.2863 - mae: 0.2863 - val_loss: 0.3201 - val_mae: 0.3201
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2857 - mae: 0.2857
Epoch 00002: val_loss improved from 0.32008 to 0.25454, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn206640.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.2712 - mae: 0.2712 - val_loss: 0.2545 - val_mae: 0.2545
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2645 - mae: 0.2645
Epoch 00003: val_loss did not improve from 0.25454
16/16 [==============================] - 0s 10ms/step - loss: 0.2511 - mae: 0.2511 - val_loss: 0.2682 - val_mae: 0.2682

 93%|█████████▎| 343/370 [1:20:08<05:53, 13.09s/it]

[[17084.104 17175.613 17174.121 17172.326 16931.375]]
0.015872178724499503
Epoch 1/100
16/16 [==============================] - ETA: 0s - loss: 0.3055 - mae: 0.3055
Epoch 00001: val_loss improved from inf to 0.25286, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn015750.h5
16/16 [==============================] - 5s 65ms/step - loss: 0.3055 - mae: 0.3055 - val_loss: 0.2529 - val_mae: 0.2529
Epoch 2/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2642 - mae: 0.2642
Epoch 00002: val_loss did not improve from 0.25286
16/16 [==============================] - 0s 10ms/step - loss: 0.2590 - mae: 0.2590 - val_loss: 0.2917 - val_mae: 0.2917
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.3260 - mae: 0.3260
Epoch 00003: val_loss did not improve from 0.25286
16/16 [==============================] - 0s 11ms/step - loss: 0.2890 - mae: 0.2890 - val_loss: 0.3159 - val_mae: 0.3159
Epoch 4/100
13/16 [=======================>......] - ETA: 0s - loss: 0

 93%|█████████▎| 344/370 [1:20:27<06:25, 14.81s/it]

[[6052.4644 6061.231  6054.2446 6025.346  6004.823 ]]
0.0058055641357014146
Epoch 1/100
13/16 [=======================>......] - ETA: 0s - loss: 0.3701 - mae: 0.3701
Epoch 00001: val_loss improved from inf to 0.29888, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn060720.h5
16/16 [==============================] - 6s 66ms/step - loss: 0.3502 - mae: 0.3502 - val_loss: 0.2989 - val_mae: 0.2989
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.3062 - mae: 0.3062
Epoch 00002: val_loss did not improve from 0.29888
16/16 [==============================] - 0s 11ms/step - loss: 0.2942 - mae: 0.2942 - val_loss: 0.3376 - val_mae: 0.3376
Epoch 3/100
12/16 [=====================>........] - ETA: 0s - loss: 0.2903 - mae: 0.2903
Epoch 00003: val_loss improved from 0.29888 to 0.28383, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn060720.h5
16/16 [==============================] - 0s 17ms/step - loss: 0.2677 - mae: 0.2677 - val_loss: 0.2838 - val_mae: 

 93%|█████████▎| 345/370 [1:20:44<06:23, 15.34s/it]

[[23138.621 23116.533 23371.451 23419.578 23444.   ]]
0.014103556957507275
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2306 - mae: 0.2306
Epoch 00001: val_loss improved from inf to 0.21077, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn043150.h5
16/16 [==============================] - 6s 70ms/step - loss: 0.2418 - mae: 0.2418 - val_loss: 0.2108 - val_mae: 0.2108
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2441 - mae: 0.2441
Epoch 00002: val_loss improved from 0.21077 to 0.17695, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn043150.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.2467 - mae: 0.2467 - val_loss: 0.1769 - val_mae: 0.1769
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2365 - mae: 0.2365
Epoch 00003: val_loss did not improve from 0.17695
16/16 [==============================] - 0s 11ms/step - loss: 0.2294 - mae: 0.2294 - val_loss: 0.1804 - val_mae: 0

 94%|█████████▎| 346/370 [1:20:54<05:29, 13.72s/it]

[[40268.59  40196.85  40365.37  40556.25  40424.117]]
0.010565112888654363
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2489 - mae: 0.2489
Epoch 00001: val_loss improved from inf to 0.30153, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn006730.h5
16/16 [==============================] - 5s 65ms/step - loss: 0.2432 - mae: 0.2432 - val_loss: 0.3015 - val_mae: 0.3015
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2336 - mae: 0.2336
Epoch 00002: val_loss improved from 0.30153 to 0.24635, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn006730.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.2297 - mae: 0.2297 - val_loss: 0.2463 - val_mae: 0.2463
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2620 - mae: 0.2620
Epoch 00003: val_loss improved from 0.24635 to 0.18817, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn006730.h5
16/16 [==============================]

 94%|█████████▍| 347/370 [1:21:06<05:03, 13.17s/it]

[[8837.171 8857.78  8867.053 8842.427 8784.819]]
0.010456978251062678
Epoch 1/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3385 - mae: 0.3385
Epoch 00001: val_loss improved from inf to 0.47248, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn089030.h5
16/16 [==============================] - 5s 66ms/step - loss: 0.3370 - mae: 0.3370 - val_loss: 0.4725 - val_mae: 0.4725
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.4410 - mae: 0.4410
Epoch 00002: val_loss improved from 0.47248 to 0.37760, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn089030.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.4221 - mae: 0.4221 - val_loss: 0.3776 - val_mae: 0.3776
Epoch 3/100
12/16 [=====================>........] - ETA: 0s - loss: 0.4213 - mae: 0.4213
Epoch 00003: val_loss improved from 0.37760 to 0.31294, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn089030.h5
16/16 [==============================] - 0s

 94%|█████████▍| 348/370 [1:21:21<05:04, 13.85s/it]

[[20354.848 20271.086 20280.133 20602.184 20862.664]]
0.02275747593798418
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2804 - mae: 0.2804
Epoch 00001: val_loss improved from inf to 0.23757, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn348150.h5
16/16 [==============================] - 5s 66ms/step - loss: 0.2799 - mae: 0.2799 - val_loss: 0.2376 - val_mae: 0.2376
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2342 - mae: 0.2342
Epoch 00002: val_loss did not improve from 0.23757
16/16 [==============================] - 0s 11ms/step - loss: 0.2205 - mae: 0.2205 - val_loss: 0.2780 - val_mae: 0.2780
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2316 - mae: 0.2316
Epoch 00003: val_loss did not improve from 0.23757
16/16 [==============================] - 0s 11ms/step - loss: 0.2163 - mae: 0.2163 - val_loss: 0.2885 - val_mae: 0.2885
Epoch 4/100
14/16 [=========================>....] - ETA: 0s - loss: 0.

 94%|█████████▍| 349/370 [1:21:36<04:56, 14.10s/it]

[[25358.746 25589.55  25603.154 25434.404 25289.184]]
0.00865918629299699
Epoch 1/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3483 - mae: 0.3483
Epoch 00001: val_loss improved from inf to 0.22169, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn319400.h5
16/16 [==============================] - 6s 68ms/step - loss: 0.3472 - mae: 0.3472 - val_loss: 0.2217 - val_mae: 0.2217
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2916 - mae: 0.2916
Epoch 00002: val_loss did not improve from 0.22169
16/16 [==============================] - 0s 10ms/step - loss: 0.2698 - mae: 0.2698 - val_loss: 0.2287 - val_mae: 0.2287
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2272 - mae: 0.2272
Epoch 00003: val_loss improved from 0.22169 to 0.21412, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn319400.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.2195 - mae: 0.2195 - val_loss: 0.2141 - val_mae: 0.

 95%|█████████▍| 350/370 [1:21:51<04:48, 14.41s/it]

[[3326.3523 3338.4338 3344.895  3357.522  3359.0486]]
0.008264673823594467
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3537 - mae: 0.3537
Epoch 00001: val_loss improved from inf to 0.27008, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn232140.h5
16/16 [==============================] - 5s 65ms/step - loss: 0.3460 - mae: 0.3460 - val_loss: 0.2701 - val_mae: 0.2701
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2837 - mae: 0.2837
Epoch 00002: val_loss did not improve from 0.27008
16/16 [==============================] - 0s 11ms/step - loss: 0.2715 - mae: 0.2715 - val_loss: 0.2787 - val_mae: 0.2787
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2593 - mae: 0.2593
Epoch 00003: val_loss improved from 0.27008 to 0.25618, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn232140.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.2463 - mae: 0.2463 - val_loss: 0.2562 - val_mae: 0

 95%|█████████▍| 351/370 [1:22:04<04:29, 14.20s/it]

[[5271.4946 5278.0186 5259.015  5361.5776 5360.4463]]
0.029236106654884197
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3623 - mae: 0.3623
Epoch 00001: val_loss improved from inf to 0.31560, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn083790.h5
16/16 [==============================] - 5s 65ms/step - loss: 0.3576 - mae: 0.3576 - val_loss: 0.3156 - val_mae: 0.3156
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.4460 - mae: 0.4460
Epoch 00002: val_loss improved from 0.31560 to 0.26444, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn083790.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.4319 - mae: 0.4319 - val_loss: 0.2644 - val_mae: 0.2644
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.3363 - mae: 0.3363
Epoch 00003: val_loss did not improve from 0.26444
16/16 [==============================] - 0s 11ms/step - loss: 0.3354 - mae: 0.3354 - val_loss: 0.3484 - val_mae: 0

 95%|█████████▌| 352/370 [1:22:32<05:25, 18.08s/it]

[[7051.851  7051.01   7048.5044 7043.7153 7042.2837]]
0.016578936844990705
Epoch 1/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3602 - mae: 0.3602
Epoch 00001: val_loss improved from inf to 0.26154, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn299030.h5
16/16 [==============================] - 5s 69ms/step - loss: 0.3459 - mae: 0.3459 - val_loss: 0.2615 - val_mae: 0.2615
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2514 - mae: 0.2514
Epoch 00002: val_loss did not improve from 0.26154
16/16 [==============================] - 0s 11ms/step - loss: 0.2414 - mae: 0.2414 - val_loss: 0.2793 - val_mae: 0.2793
Epoch 3/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2672 - mae: 0.2672
Epoch 00003: val_loss did not improve from 0.26154
16/16 [==============================] - 0s 10ms/step - loss: 0.2638 - mae: 0.2638 - val_loss: 0.2632 - val_mae: 0.2632
Epoch 4/100
14/16 [=========================>....] - ETA: 0s - loss: 0

 95%|█████████▌| 353/370 [1:22:48<05:00, 17.65s/it]

[[51805.867 51932.133 51989.383 51847.05  51619.6  ]]
0.013307163856946719
Epoch 1/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3818 - mae: 0.3818
Epoch 00001: val_loss improved from inf to 0.28403, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn049070.h5
16/16 [==============================] - 6s 66ms/step - loss: 0.3689 - mae: 0.3689 - val_loss: 0.2840 - val_mae: 0.2840
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2605 - mae: 0.2605
Epoch 00002: val_loss improved from 0.28403 to 0.26486, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn049070.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.2533 - mae: 0.2533 - val_loss: 0.2649 - val_mae: 0.2649
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2177 - mae: 0.2177
Epoch 00003: val_loss did not improve from 0.26486
16/16 [==============================] - 0s 10ms/step - loss: 0.2184 - mae: 0.2184 - val_loss: 0.2733 - val_mae: 0

 96%|█████████▌| 354/370 [1:23:08<04:50, 18.14s/it]

[[22307.201 22354.467 22473.969 22576.045 22513.627]]
0.021851976806949634
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2454 - mae: 0.2454
Epoch 00001: val_loss improved from inf to 0.49714, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn067310.h5
16/16 [==============================] - 5s 65ms/step - loss: 0.2492 - mae: 0.2492 - val_loss: 0.4971 - val_mae: 0.4971
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.4253 - mae: 0.4253
Epoch 00002: val_loss improved from 0.49714 to 0.19659, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn067310.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.4059 - mae: 0.4059 - val_loss: 0.1966 - val_mae: 0.1966
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.3349 - mae: 0.3349
Epoch 00003: val_loss improved from 0.19659 to 0.16555, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn067310.h5
16/16 [==============================]

 96%|█████████▌| 355/370 [1:23:17<03:55, 15.69s/it]

[[21914.64  21912.172 21868.152 21940.805 22086.395]]
0.0162759865941648
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2446 - mae: 0.2446
Epoch 00001: val_loss improved from inf to 0.21669, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn036030.h5
16/16 [==============================] - 5s 67ms/step - loss: 0.2466 - mae: 0.2466 - val_loss: 0.2167 - val_mae: 0.2167
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2096 - mae: 0.2096
Epoch 00002: val_loss improved from 0.21669 to 0.20385, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn036030.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.2145 - mae: 0.2145 - val_loss: 0.2039 - val_mae: 0.2039
Epoch 3/100
12/16 [=====================>........] - ETA: 0s - loss: 0.1884 - mae: 0.1884
Epoch 00003: val_loss improved from 0.20385 to 0.20141, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn036030.h5
16/16 [==============================] -

 96%|█████████▌| 356/370 [1:23:37<03:56, 16.88s/it]

[[9333.807 9313.956 9307.707 9301.825 9095.147]]
0.02199719830423264
Epoch 1/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3969 - mae: 0.3969
Epoch 00001: val_loss improved from inf to 0.21308, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn031390.h5
16/16 [==============================] - 5s 67ms/step - loss: 0.3844 - mae: 0.3844 - val_loss: 0.2131 - val_mae: 0.2131
Epoch 2/100
12/16 [=====================>........] - ETA: 0s - loss: 0.2363 - mae: 0.2363
Epoch 00002: val_loss did not improve from 0.21308
16/16 [==============================] - 0s 11ms/step - loss: 0.2185 - mae: 0.2185 - val_loss: 0.2242 - val_mae: 0.2242
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2641 - mae: 0.2641
Epoch 00003: val_loss did not improve from 0.21308
16/16 [==============================] - 0s 11ms/step - loss: 0.2511 - mae: 0.2511 - val_loss: 0.3537 - val_mae: 0.3537
Epoch 4/100
12/16 [=====================>........] - ETA: 0s - loss: 0.2646 

 96%|█████████▋| 357/370 [1:23:50<03:25, 15.78s/it]

[[38550.508 38550.566 38550.598 38550.54  38550.473]]
1.3922665369649809e-05
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3103 - mae: 0.3103
Epoch 00001: val_loss improved from inf to 0.26417, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn121800.h5
16/16 [==============================] - 6s 66ms/step - loss: 0.3038 - mae: 0.3038 - val_loss: 0.2642 - val_mae: 0.2642
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.3061 - mae: 0.3061
Epoch 00002: val_loss improved from 0.26417 to 0.16624, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn121800.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.2824 - mae: 0.2824 - val_loss: 0.1662 - val_mae: 0.1662
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3225 - mae: 0.3225
Epoch 00003: val_loss improved from 0.16624 to 0.16347, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn121800.h5
16/16 [=============================

 97%|█████████▋| 358/370 [1:24:03<02:58, 14.85s/it]

[[15906.348 15803.556 15870.479 15811.172 16014.835]]
0.06031572649308653
Epoch 1/100
16/16 [==============================] - ETA: 0s - loss: 0.2692 - mae: 0.2692
Epoch 00001: val_loss improved from inf to 0.27600, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn033310.h5
16/16 [==============================] - 5s 64ms/step - loss: 0.2692 - mae: 0.2692 - val_loss: 0.2760 - val_mae: 0.2760
Epoch 2/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3793 - mae: 0.3793
Epoch 00002: val_loss improved from 0.27600 to 0.21211, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn033310.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.3731 - mae: 0.3731 - val_loss: 0.2121 - val_mae: 0.2121
Epoch 3/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3638 - mae: 0.3638
Epoch 00003: val_loss did not improve from 0.21211
16/16 [==============================] - 0s 11ms/step - loss: 0.3507 - mae: 0.3507 - val_loss: 0.2147 - val_mae: 0.

 97%|█████████▋| 359/370 [1:24:13<02:25, 13.25s/it]

[[10393.315 10463.684 10627.459 11016.232 10640.531]]
0.039944767568750525
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2867 - mae: 0.2867
Epoch 00001: val_loss improved from inf to 0.23418, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn086390.h5
16/16 [==============================] - 5s 68ms/step - loss: 0.2944 - mae: 0.2944 - val_loss: 0.2342 - val_mae: 0.2342
Epoch 2/100
12/16 [=====================>........] - ETA: 0s - loss: 0.2605 - mae: 0.2605
Epoch 00002: val_loss improved from 0.23418 to 0.18003, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn086390.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.2834 - mae: 0.2834 - val_loss: 0.1800 - val_mae: 0.1800
Epoch 3/100
11/16 [===================>..........] - ETA: 0s - loss: 0.2921 - mae: 0.2921
Epoch 00003: val_loss did not improve from 0.18003
16/16 [==============================] - 0s 12ms/step - loss: 0.2782 - mae: 0.2782 - val_loss: 0.1803 - val_mae: 0

 97%|█████████▋| 360/370 [1:24:29<02:22, 14.20s/it]

[[28784.223 28682.443 28743.152 29009.492 29313.875]]
0.020560879725781973
Epoch 1/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2570 - mae: 0.2570
Epoch 00001: val_loss improved from inf to 0.21991, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn078020.h5
16/16 [==============================] - 6s 66ms/step - loss: 0.2591 - mae: 0.2591 - val_loss: 0.2199 - val_mae: 0.2199
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3274 - mae: 0.3274
Epoch 00002: val_loss improved from 0.21991 to 0.18517, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn078020.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.3091 - mae: 0.3091 - val_loss: 0.1852 - val_mae: 0.1852
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3865 - mae: 0.3865
Epoch 00003: val_loss did not improve from 0.18517
16/16 [==============================] - 0s 11ms/step - loss: 0.3987 - mae: 0.3987 - val_loss: 0.2127 - val_mae: 0

 98%|█████████▊| 361/370 [1:24:46<02:15, 15.04s/it]

[[8992.401 9007.62  9015.542 9020.587 9017.484]]
0.004276589337440867
Epoch 1/100
16/16 [==============================] - ETA: 0s - loss: 0.3942 - mae: 0.3942
Epoch 00001: val_loss improved from inf to 0.38440, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn102710.h5
16/16 [==============================] - 6s 67ms/step - loss: 0.3942 - mae: 0.3942 - val_loss: 0.3844 - val_mae: 0.3844
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3298 - mae: 0.3298
Epoch 00002: val_loss did not improve from 0.38440
16/16 [==============================] - 0s 10ms/step - loss: 0.3118 - mae: 0.3118 - val_loss: 0.4275 - val_mae: 0.4275
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3134 - mae: 0.3134
Epoch 00003: val_loss improved from 0.38440 to 0.32637, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn102710.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.3095 - mae: 0.3095 - val_loss: 0.3264 - val_mae: 0.3264

 98%|█████████▊| 362/370 [1:24:59<01:56, 14.51s/it]

[[28822.668 28945.29  28985.283 28972.096 28978.66 ]]
0.006225023818098924
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.4097 - mae: 0.4097
Epoch 00001: val_loss improved from inf to 0.50946, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn314130.h5
16/16 [==============================] - 5s 67ms/step - loss: 0.4050 - mae: 0.4050 - val_loss: 0.5095 - val_mae: 0.5095
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.5043 - mae: 0.5043
Epoch 00002: val_loss improved from 0.50946 to 0.26275, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn314130.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.4959 - mae: 0.4959 - val_loss: 0.2628 - val_mae: 0.2628
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.3170 - mae: 0.3170
Epoch 00003: val_loss did not improve from 0.26275
16/16 [==============================] - 0s 11ms/step - loss: 0.2925 - mae: 0.2925 - val_loss: 0.3727 - val_mae: 0

 98%|█████████▊| 363/370 [1:25:14<01:42, 14.69s/it]

[[36959.152 36846.19  38034.836 38309.312 38305.68 ]]
0.018958506863211693
Epoch 1/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2995 - mae: 0.2995
Epoch 00001: val_loss improved from inf to 0.35128, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn035890.h5
16/16 [==============================] - 5s 67ms/step - loss: 0.2943 - mae: 0.2943 - val_loss: 0.3513 - val_mae: 0.3513
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.5074 - mae: 0.5074
Epoch 00002: val_loss improved from 0.35128 to 0.26960, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn035890.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.4974 - mae: 0.4974 - val_loss: 0.2696 - val_mae: 0.2696
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.4341 - mae: 0.4341
Epoch 00003: val_loss improved from 0.26960 to 0.23606, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn035890.h5
16/16 [==============================]

 98%|█████████▊| 364/370 [1:25:26<01:22, 13.75s/it]

[[1834.4335 1833.3394 1849.0009 1847.9838 1848.9314]]
0.01673721777535614
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.4068 - mae: 0.4068
Epoch 00001: val_loss improved from inf to 0.34455, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn032620.h5
16/16 [==============================] - 6s 65ms/step - loss: 0.4024 - mae: 0.4024 - val_loss: 0.3446 - val_mae: 0.3446
Epoch 2/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3810 - mae: 0.3810
Epoch 00002: val_loss improved from 0.34455 to 0.32812, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn032620.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.3728 - mae: 0.3728 - val_loss: 0.3281 - val_mae: 0.3281
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2830 - mae: 0.2830
Epoch 00003: val_loss improved from 0.32812 to 0.30303, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn032620.h5
16/16 [==============================] 

 99%|█████████▊| 365/370 [1:25:36<01:03, 12.77s/it]

[[7857.73   7891.9526 7937.294  7851.005  7939.482 ]]
0.018126778805957495
Epoch 1/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2625 - mae: 0.2625
Epoch 00001: val_loss improved from inf to 0.44126, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn220630.h5
16/16 [==============================] - 6s 67ms/step - loss: 0.2577 - mae: 0.2577 - val_loss: 0.4413 - val_mae: 0.4413
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.4422 - mae: 0.4422
Epoch 00002: val_loss improved from 0.44126 to 0.22135, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn220630.h5
16/16 [==============================] - 0s 17ms/step - loss: 0.4612 - mae: 0.4612 - val_loss: 0.2213 - val_mae: 0.2213
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2122 - mae: 0.2122
Epoch 00003: val_loss improved from 0.22135 to 0.18664, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn220630.h5
16/16 [==============================]

 99%|█████████▉| 366/370 [1:25:47<00:47, 12.00s/it]

[[4958.613  4953.2446 4956.038  4957.7515 4968.093 ]]
0.004962969433449632
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3270 - mae: 0.3270
Epoch 00001: val_loss improved from inf to 0.23684, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn064260.h5
16/16 [==============================] - 5s 65ms/step - loss: 0.3305 - mae: 0.3305 - val_loss: 0.2368 - val_mae: 0.2368
Epoch 2/100
15/16 [===========================>..] - ETA: 0s - loss: 0.2920 - mae: 0.2920
Epoch 00002: val_loss did not improve from 0.23684
16/16 [==============================] - 0s 10ms/step - loss: 0.2858 - mae: 0.2858 - val_loss: 0.3123 - val_mae: 0.3123
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.2517 - mae: 0.2517
Epoch 00003: val_loss improved from 0.23684 to 0.19605, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn064260.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.2313 - mae: 0.2313 - val_loss: 0.1961 - val_mae: 0

 99%|█████████▉| 367/370 [1:26:00<00:37, 12.53s/it]

[[8400.694 8253.035 8517.136 8422.682 8628.228]]
0.05416730312630519
Epoch 1/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2344 - mae: 0.2344
Epoch 00001: val_loss improved from inf to 0.26517, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn287410.h5
16/16 [==============================] - 5s 67ms/step - loss: 0.2610 - mae: 0.2610 - val_loss: 0.2652 - val_mae: 0.2652
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3754 - mae: 0.3754
Epoch 00002: val_loss improved from 0.26517 to 0.26076, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn287410.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.4109 - mae: 0.4109 - val_loss: 0.2608 - val_mae: 0.2608
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2768 - mae: 0.2768
Epoch 00003: val_loss improved from 0.26076 to 0.23988, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn287410.h5
16/16 [==============================] - 0s 

 99%|█████████▉| 368/370 [1:26:27<00:33, 16.78s/it]

[[7157.744  7118.2305 7243.876  7186.9795 7011.0483]]
0.03322612049283727
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3036 - mae: 0.3036
Epoch 00001: val_loss improved from inf to 0.27963, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn110790.h5
16/16 [==============================] - 6s 68ms/step - loss: 0.3231 - mae: 0.3231 - val_loss: 0.2796 - val_mae: 0.2796
Epoch 2/100
14/16 [=========================>....] - ETA: 0s - loss: 0.3785 - mae: 0.3785
Epoch 00002: val_loss improved from 0.27963 to 0.26340, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn110790.h5
16/16 [==============================] - 0s 16ms/step - loss: 0.3982 - mae: 0.3982 - val_loss: 0.2634 - val_mae: 0.2634
Epoch 3/100
13/16 [=======================>......] - ETA: 0s - loss: 0.3200 - mae: 0.3200
Epoch 00003: val_loss improved from 0.26340 to 0.25123, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn110790.h5
16/16 [==============================] 

100%|█████████▉| 369/370 [1:26:44<00:16, 16.79s/it]

[[41778.445 41909.188 41861.28  41814.605 41731.492]]
0.004685212548651252
Epoch 1/100
15/16 [===========================>..] - ETA: 0s - loss: 0.3382 - mae: 0.3382
Epoch 00001: val_loss improved from inf to 0.32126, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn099320.h5
16/16 [==============================] - 6s 68ms/step - loss: 0.3402 - mae: 0.3402 - val_loss: 0.3213 - val_mae: 0.3213
Epoch 2/100
13/16 [=======================>......] - ETA: 0s - loss: 0.3477 - mae: 0.3477
Epoch 00002: val_loss improved from 0.32126 to 0.25157, saving model to /content/drive/MyDrive/stock_2/rnn_public/rnn099320.h5
16/16 [==============================] - 0s 15ms/step - loss: 0.3255 - mae: 0.3255 - val_loss: 0.2516 - val_mae: 0.2516
Epoch 3/100
14/16 [=========================>....] - ETA: 0s - loss: 0.2957 - mae: 0.2957
Epoch 00003: val_loss did not improve from 0.25157
16/16 [==============================] - 0s 11ms/step - loss: 0.2787 - mae: 0.2787 - val_loss: 0.2571 - val_mae: 0

100%|██████████| 370/370 [1:27:05<00:00, 14.12s/it]

[[48565.664 48507.152 47252.47  48103.457 48570.168]]
0.03565708541620862


In [12]:
# nmae 평균
nmae_result = np.array(nmae_df['nmae'])

In [13]:
np.mean(nmae_result)

0.017289364963000608

# Private

In [14]:
start_date = '20210104'
end_date = '20211126'

start_weekday = pd.to_datetime(start_date).weekday()
max_weeknum = pd.to_datetime(end_date).strftime('%V')
business_days = pd.DataFrame(pd.date_range(start_date,end_date,freq='B'), columns = ['Date'])

In [15]:
def RNN_model(X_train, y_train, X_val, y_val):

  model = Sequential()
  model.add(SimpleRNN(units = 1, input_shape = (X_train.shape[1], 1), activation = 'tanh', return_sequences = True))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))
  model.add(SimpleRNN(units = 8, activation = 'tanh', return_sequences = True))
  model.add(Dropout(rate = 0.125))

  model.add(TimeDistributed(Dense(units = 1)))

  model.compile(optimizer = Adam(learning_rate = 0.01), loss = 'mean_absolute_error', metrics=['mae']) 

  es = EarlyStopping(monitor ='val_loss', mode ='min', verbose = 1, patience = 10)
  model_save_folder_path = '/content/drive/MyDrive/stock_2/rnn_private/rnn'
  model_path = model_save_folder_path + f'{code}.h5'
  mc = ModelCheckpoint(model_path, monitor ='val_loss', mode ='min', verbose = 1, save_best_only = True)

  model.fit(X_train, y_train, epochs = 100, batch_size = 2, verbose = 1, shuffle = False, callbacks = [es, mc],
                      validation_data=(X_val, y_val))

  return model

In [18]:
import warnings
warnings.filterwarnings("ignore")

for code in tqdm(stock_list['종목코드'].values):
  tf.random.set_seed(1234)
  
  # 해당 종목의 데이터 가져온 후 주 단위 데이터로 나타내기
  stock_price = fdr.DataReader(code, start = start_date, end = end_date)[['Close']].reset_index()
  stock_price = pd.merge(business_days, stock_price, how = 'outer')
  stock_price['weekday'] = stock_price.Date.apply(lambda x : x.weekday())
  stock_price['weeknum'] = stock_price.Date.apply(lambda x : x.strftime('%V'))
  stock_price.Close = stock_price.Close.ffill()
  stock_price = pd.pivot_table(data = stock_price, values = 'Close', columns = 'weekday', index = 'weeknum')

  X_train = stock_price.iloc[0:-12].to_numpy()
  X_val = stock_price.iloc[-12:-2].to_numpy()
  X_test = stock_price.iloc[-2].to_numpy()

  y_train = stock_price.iloc[1:-11].to_numpy()
  y_val = stock_price.iloc[-11:-1].to_numpy()
  y_test = stock_price.iloc[-1].to_numpy()

  # 스케일링 시행
  scaler = MinMaxScaler()

  X_train_scaled = scaler.fit_transform(X_train.reshape(-1, 1)).reshape(35, 5)
  X_val_scaled = scaler.fit_transform(X_val.reshape(-1, 1)).reshape(10, 5)
  X_test_scaled = scaler.fit_transform(X_test.reshape(-1, 1)).reshape(1, 5)

  y_train_scaled = scaler.fit_transform(y_train.reshape(-1, 1)).reshape(35, 5)
  y_val_scaled = scaler.fit_transform(y_val.reshape(-1, 1)).reshape(10, 5)
  y_test_scaled = scaler.fit_transform(y_test.reshape(-1, 1)).reshape(1, 5)

  X_train_scaled = np.reshape(X_train_scaled, (X_train_scaled.shape[0], X_train_scaled.shape[1]))
  X_val_scaled = np.reshape(X_val_scaled, (X_val_scaled.shape[0], X_val_scaled.shape[1]))
  X_test_scaled = np.reshape(X_test_scaled, (X_test_scaled.shape[0], X_test_scaled.shape[1]))
  
  # 모델 학습
  model = RNN_model(X_train_scaled, y_train_scaled, X_val_scaled, y_val_scaled)
  model = keras.models.load_model(f"/content/drive/MyDrive/stock_2/rnn_private/rnn{code}.h5")

  # 예측
  y_pred = model.predict(X_test_scaled)
  y_pred = y_pred.reshape(1,5)
  y_pred = scaler.inverse_transform(y_pred)

  nmae = np.mean(np.abs(y_test - y_pred) / y_test)

  nmae_df = nmae_df.append({'code' : code, 'nmae' : nmae}, ignore_index = True)
  
  print(y_pred)
  print(nmae)
    
  for i in range (0, 5):
    submission.loc[i + 5, code] = y_pred[0][i]

16/18 [=========================>....] - ETA: 0s - loss: 0.2610 - mae: 0.2610
Epoch 00001: val_loss improved from inf to 0.43513, saving model to /content/drive/MyDrive/stock_2/rnn_private/rnn287410.h5
18/18 [==============================] - 6s 61ms/step - loss: 0.2685 - mae: 0.2685 - val_loss: 0.4351 - val_mae: 0.4351
Epoch 2/100
13/18 [====================>.........] - ETA: 0s - loss: 0.4538 - mae: 0.4538
Epoch 00002: val_loss improved from 0.43513 to 0.24848, saving model to /content/drive/MyDrive/stock_2/rnn_private/rnn287410.h5
18/18 [==============================] - 0s 15ms/step - loss: 0.4943 - mae: 0.4943 - val_loss: 0.2485 - val_mae: 0.2485
Epoch 3/100
18/18 [==============================] - ETA: 0s - loss: 0.2691 - mae: 0.2691
Epoch 00003: val_loss did not improve from 0.24848
18/18 [==============================] - 0s 12ms/step - loss: 0.2691 - mae: 0.2691 - val_loss: 0.3271 - val_mae: 0.3271
Epoch 4/100
17/18 [===========================>..] - ETA: 0s - loss: 0.3801 - m

 99%|█████████▉| 368/370 [1:35:55<00:27, 13.85s/it]

[[6364.0874 6328.3438 6301.471  6378.7163 6365.6724]]
0.02149998461170053
Epoch 1/100
15/18 [========================>.....] - ETA: 0s - loss: 0.3036 - mae: 0.3036
Epoch 00001: val_loss improved from inf to 0.32646, saving model to /content/drive/MyDrive/stock_2/rnn_private/rnn110790.h5
18/18 [==============================] - 6s 64ms/step - loss: 0.3272 - mae: 0.3272 - val_loss: 0.3265 - val_mae: 0.3265
Epoch 2/100
17/18 [===========================>..] - ETA: 0s - loss: 0.3855 - mae: 0.3855
Epoch 00002: val_loss improved from 0.32646 to 0.32566, saving model to /content/drive/MyDrive/stock_2/rnn_private/rnn110790.h5
18/18 [==============================] - 0s 16ms/step - loss: 0.3826 - mae: 0.3826 - val_loss: 0.3257 - val_mae: 0.3257
Epoch 3/100
17/18 [===========================>..] - ETA: 0s - loss: 0.3811 - mae: 0.3811
Epoch 00003: val_loss did not improve from 0.32566
18/18 [==============================] - 0s 12ms/step - loss: 0.3737 - mae: 0.3737 - val_loss: 0.3476 - val_mae: 

100%|█████████▉| 369/370 [1:36:06<00:13, 13.04s/it]

[[47993.04  47708.85  47893.902 47682.68  47849.87 ]]
0.026088466007885724
Epoch 1/100
18/18 [==============================] - ETA: 0s - loss: 0.3345 - mae: 0.3345
Epoch 00001: val_loss improved from inf to 0.32674, saving model to /content/drive/MyDrive/stock_2/rnn_private/rnn099320.h5
18/18 [==============================] - 6s 88ms/step - loss: 0.3345 - mae: 0.3345 - val_loss: 0.3267 - val_mae: 0.3267
Epoch 2/100
18/18 [==============================] - ETA: 0s - loss: 0.2976 - mae: 0.2976
Epoch 00002: val_loss improved from 0.32674 to 0.32419, saving model to /content/drive/MyDrive/stock_2/rnn_private/rnn099320.h5
18/18 [==============================] - 0s 16ms/step - loss: 0.2976 - mae: 0.2976 - val_loss: 0.3242 - val_mae: 0.3242
Epoch 3/100
13/18 [====================>.........] - ETA: 0s - loss: 0.3061 - mae: 0.3061
Epoch 00003: val_loss improved from 0.32419 to 0.31516, saving model to /content/drive/MyDrive/stock_2/rnn_private/rnn099320.h5
18/18 [============================

100%|██████████| 370/370 [1:36:18<00:00, 15.62s/it]

[[46650.887 46720.7   46559.22  46742.746 46701.95 ]]
0.016873897883689613


In [19]:
submission.isna().sum().sum()

0

In [20]:
submission

Day        000060  ...        363280        950130
0  2021-11-01  29059.160156  ...  26431.703125  17880.105469
1  2021-11-02  29288.392578  ...  26702.648438  17867.044922
2  2021-11-03  29443.205078  ...  26779.953125  17888.453125
3  2021-11-04  29353.425781  ...  26692.367188  17784.464844
4  2021-11-05  28742.460938  ...  26559.785156  17670.412109
5  2021-11-29  30026.546875  ...  25370.287109  15741.738281
6  2021-11-30  30207.595703  ...  25400.347656  15670.024414
7  2021-12-01  30253.546875  ...  25254.966797  15733.010742
8  2021-12-02  30050.435547  ...  25304.572266  15594.787109
9  2021-12-03  30126.240234  ...  25378.585938  15603.372070

[10 rows x 371 columns]

In [21]:
submission.to_csv("/content/drive/MyDrive/stock_2/submission_rnn.csv", index = False)